### ISSUE TITLE
Error opening html file for preview

### ISSUE THREAD

**Issue by CameronGo** [blzjns/vscode-raml#3]
When I attempt to use the Preview feature, I get a couple of messages noted in VS Code and it cannot open the resulting html file.  When I manually go to find the file I see it is there and I can open it in my browser manually. 

![image](https://cloud.githubusercontent.com/assets/14074983/19660962/e0a3a248-99ff-11e6-9321-6dfef26320a2.png)

**Comment by blzjns** [comment]
Hi @CameronGo, thanks for your feedback! It should be fixed in the new version. Please ensure the **raml2html** version you have installed also supports the RAML version you are using. :)
