### ISSUE TITLE
Preview support for RAML 1.0

### ISSUE THREAD

**Issue by uchoa** [blzjns/vscode-raml#4]
I get a "version validation" error when trying to preview a RAML 1.0 file. I suppose it is because you really don't support version 1.0 yet and not a bug. Is version 1.0 support on its way?

**Comment by blzjns** [comment]
Hi @uchoa , **raml2html** so far only supports RAML 0.8. Fortunately, a support version for RAML 1.0 is in development and about to be released, for further info (see [#254](https://github.com/raml2html/raml2html/issues/254)) 

Cheers!

**Comment by jaime-olivares** [comment]
I think the message shall be more explicit, at least "RAML version validation error". The current message could mean anything.
