### ISSUE TITLE
RAML 1.0 suppport

### ISSUE THREAD

**Issue by rnemec** [blzjns/vscode-raml#5]
When trying to preview RAML 1.0 file, it fails with "version validation" error.

**Comment by rdecarlo73** [comment]
Looks like raml2html 4 is required.  Can you switch the dependency?

**Comment by blzjns** [comment]
Hey guys, thanks for your suggestions. I'll soon start working on those updates.

**Comment by blzjns** [comment]
Hi, thanks again for your suggestions! RAML 1.0 support was implemented in version 3.0.0. However, now **raml2html** must be installed separately; thus, please ensure the **raml2html** version you have installed also supports the RAML version you are using. :)
