### ISSUE TITLE
Should we combine efforts for vscode on RAML

### ISSUE THREAD

**Issue by sichvoge** [blzjns/vscode-raml#6]
Hi,

I happen to come across @jlandersen extension as well and wonder if we should combine our efforts to add RAML 1.0 support instead of maintain two separated repositories. We could add what has been done here to https://github.com/jlandersen/vscode-raml and continue to improve the support on only one.

I also know that some guys are working on a language server for vscode which we can use as well for validation and other cool stuff.

What do you think?

Thanks,
Christian

**Comment by blzjns** [comment]
Hi @sichvoge, thanks for your suggestion! RAML 1.0 support was added in version 3.0.0. However, now raml2html must be installed separately; thus, please ensure the **raml2html** version you have installed also supports the RAML version you are using. :)

**Comment by deduper** [comment]
Hey @sichvoge? Any news on that language server you talked about back then? I'm curious to see what it can do.

TIA :+1: 



_**EDIT**_: Ah! OK. Never mind. [_Found it_](https://github.com/mulesoft-labs/raml-language-server). Looks like it's an even [_lonelier ghost town_](https://github.com/blzjns/vscode-raml/issues/17#issue-419094081) than this one ;)
